# Application properties
server:
  port: 10510

spring:
  application:
    name: vuvib-signer-backend
  datasource:
    username: sa
    url: jdbc:h2:file:./testdb
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
      path: ${path.apiResource.v1}/h2-ui
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: 'false'
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'

keystore:
  type: PKCS12
  directory: /vuvib/keystore

hash:
  algorithm: SHA256

signature:
  append: true
  visible: true
  page: 1
  fontsize: 6.0
  position:
    llx: 10
    lly: 10
    urx: 120
    ury: 70

file:
  directory:
    unsigned: /vuvib/unsigned
    signed: /vuvib/signed

bezkoder:
  app:
    jwtCookieName: vuvib
    jwtSecret: vuvibSecretKey
    jwtExpirationMs: 86400000

path:
  apiResource:
    v1: /signer/api/v1

api:
  usuarios:
    url: https://testvuv.tech/ws/api/v1/usuarios
  firma:
    url: https://testvuv.tech/ws/api/v1/detallefirma
  documentos:
    url: https://testvuv.tech/ws/documentos
